  backend:
    name: git-gateway
    branch: master

  publish_mode: editorial_workflow
  media_folder: static/uploads
  public_folder: /uploads
  media_library:
    config:
      multiple: true

  collections:
    - name: "blog"
      label: "Blog"
      folder: "static/posts"
      create: true
      fields:
        - { label: "Slug", name: "slug", widget: "string" }
        - { label: "Title", name: "title", widget: "string" }
        - { label: "Body", name: "body", widget: "markdown" }